# SITE CONFIGURATION
title: Katrina Wehr # your site title
author: Katrina Wehr # You :P
description: > # Meta description of Homepage
  The personal website and blog of Katrina Wehr.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kat-wehr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Katrina Wehr
  links:
    - https://twitter.com/katrinamwehr
    - https://www.linkedin.com/in/katmwehr
    - https://github.com/kat-wehr
   
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Katrina M. Wehr: Instructional Designer

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: katrina.m.wehr@gmail.com # email for form submission

twitter_username: katrinamwehr # replace with your_twitter_username or comment to remove link from footer
github_username:  kat-wehr # replace with your_github_username or comment to remove link from footer
instagram_username: katmwehr # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: katrinawehr # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
